[package]
name = "glyphs-reader"
version = "0.0.1"
license = "MIT/Apache-2.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kurbo = "0.5.1"
plist_derive = { path = "plist_derive" }
ordered-float = "3.4.0"

thiserror = "1.0.37"

log = "0.4"
env_logger = "0.9.0"

regex = "1.7.0"

[dev-dependencies]
pretty_assertions = "1.3.0"